"""the tables a run needs

Revision ID: 421343018093
Revises: 2b605efc34c7
Create Date: 2026-08-27 09:01:15.317616

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations.grants import ADVANCES, APPEND_ONLY, SWEEPABLE, grant

# revision identifiers, used by Alembic.
revision: str = "421343018093"
down_revision: str | Sequence[str] | None = "2b605efc34c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blobs",
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "first_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("hash"),
        comment="Candidate source, stored once however many candidates share it.",
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("response_code", sa.Integer(), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status in ('in_flight', 'done')", name="idempotency_status"
        ),
        sa.PrimaryKeyConstraint("key"),
        comment="The one table a sweeper deletes from, hence the DELETE grant.",
    )
    op.create_table(
        "manifests",
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("api_version", sa.Text(), nullable=False),
        sa.Column(
            "first_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("hash"),
        comment="The .cadence that produced a run, verbatim.",
    )
    op.create_table(
        "templates",
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "first_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("hash"),
        comment=(
            "Prompt templates by content: editing one adds a row, never changes one."
        ),
    )
    op.create_table(
        "verdicts",
        sa.Column("candidate_hash", sa.String(length=64), nullable=False),
        sa.Column("task_hash", sa.String(length=64), nullable=False),
        sa.Column("seeds_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "scored",
                "invalid",
                "crashed",
                "timed_out",
                "out_of_memory",
                "verifier_error",
                name="outcome",
            ),
            nullable=False,
        ),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("wall_ms", sa.Float(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("candidate_hash", "task_hash", "seeds_hash"),
        comment=(
            "The primary key is the cache. Sound only if the verifier is deterministic."
        ),
    )
    op.create_table(
        "budget",
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("cap_trials", sa.Integer(), nullable=True),
        sa.Column("cap_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column(
            "reserved_usd",
            sa.Numeric(precision=12, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "settled_usd",
            sa.Numeric(precision=12, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
        comment="Reserve before dispatch, settle after. Check-then-spend is two steps.",
    )
    op.create_table(
        "candidates",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("parent_id", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("alive", "retired", "quarantined", name="candidate_state"),
            nullable=False,
        ),
        sa.Column("crashes", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["code_hash"],
            ["blobs.hash"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "fingerprint"),
    )
    op.create_table(
        "events",
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "seq"),
        comment="The tape. Append-only; an event that could change is not an event.",
    )
    op.create_table(
        "quarantine",
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("crashes", sa.Integer(), nullable=False),
        sa.Column(
            "at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("fingerprint"),
        comment="Read at dispatch. A poison candidate surviving restart loops forever.",
    )
    op.create_table(
        "trials",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "started",
                "prompted",
                "generated",
                "materialized",
                "measured",
                "unusable",
                "abandoned",
                name="trial_state",
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("parent_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("owner", sa.Text(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "seq"),
    )
    op.create_table(
        "model_calls",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("trial_id", sa.Text(), nullable=True),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("template_hash", sa.String(length=64), nullable=True),
        sa.Column("recipe", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_hash"],
            ["templates.hash"],
        ),
        sa.ForeignKeyConstraint(
            ["trial_id"],
            ["trials.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment=(
            "The recipe must rebuild the prompt byte for byte, or replay is unsound."
        ),
    )
    op.add_column(
        "runs", sa.Column("manifest_hash", sa.String(length=64), nullable=True)
    )
    op.add_column("runs", sa.Column("owner", sa.Text(), nullable=True))
    op.add_column(
        "runs", sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_foreign_key(
        "runs_manifest_hash_fkey", "runs", "manifests", ["manifest_hash"], ["hash"]
    )
    # ### end Alembic commands ###

    # Everything below is hand-written: autogenerate does not know about roles,
    # and these grants are what make "the log cannot be edited" an invariant
    # rather than a habit.
    for table in (
        "blobs",
        "manifests",
        "templates",
        "verdicts",
        "events",
        "model_calls",
    ):
        grant(table, APPEND_ONLY)
    for table in ("trials", "candidates", "budget", "quarantine"):
        grant(table, ADVANCES)
    # A TTL needs a sweeper, and a sweeper needs DELETE. The only one.
    grant("idempotency_keys", SWEEPABLE)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("runs_manifest_hash_fkey", "runs", type_="foreignkey")
    op.drop_column("runs", "lease_expires_at")
    op.drop_column("runs", "owner")
    op.drop_column("runs", "manifest_hash")
    op.drop_table("model_calls")
    op.drop_table("trials")
    op.drop_table("quarantine")
    op.drop_table("events")
    op.drop_table("candidates")
    op.drop_table("budget")
    op.drop_table("verdicts")
    op.drop_table("templates")
    op.drop_table("manifests")
    op.drop_table("idempotency_keys")
    op.drop_table("blobs")
    # ### end Alembic commands ###

    # drop_table leaves the enum type behind; without this a re-upgrade fails
    # with "type already exists".
    for enum in ("trial_state", "candidate_state", "outcome"):
        sa.Enum(name=enum).drop(op.get_bind())
