name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code_standards:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      # Run all pre-commit hooks (includes ruff, black, and others as configured)
      - name: Run Pre-commit
        run: |
          pre-commit run --all-files

      - name: Run tests
        run: pytest --cov --cov-branch --cov-config=.coveragerc --cov-report=xml


      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: yash-srivastava19/cadence
